name: CI

on:
  workflow_dispatch:
  # push:
  #   branches: [ main, v2 ]
  # pull_request:
  #   branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: build and test
        run: |
          npm ci
          npm run build

      - name: generate example page by hmd2html cli
        run: |
          node dist/cli.js -i ./example/index.md
          node dist/cli.js -i ./example/index.md -k -o ./output/index.dark.html
      
      - name: generate example page by web js
        run: |
          mkdir output/js
          mv ./dist/web/hmd2html.min.js ./output/js
          mv ./example/index.html ./output/webjs.html

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output
  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
